import { DonateBand, images, PageHero, Video } from "./PageParts";
/* eslint-disable @next/next/no-img-element -- Se conservan fotografías remotas originales de Fundación Jazmín. */

export type Project = { title:string; location:string; intro:string; body:string[]; video?:string; map?:string; gallery?:number; image?:string; photos?:readonly string[] };

export const projectData: Record<string, Project> = {
  plazaportugal:{title:"Plaza Portugal",location:"Montevideo",image:images.portugal,photos:[images.portugalHamacas,images.portugalEscuela],gallery:23,video:"KUMnoRaSras",map:"https://www.google.com/maps/d/u/0/edit?hl=es&mid=1JwDjqIUl8SmUsA_IYPt-7OqAEsKyaZY&ll=-34.88117256846246%2C-56.153526871166854&z=16",intro:"En el año 2015 la Fundación Jazmín realizó el concurso de ideas “Una plaza para todos”, junto con la Facultad de Arquitectura de la Universidad de la República y la Intendencia Municipal de Montevideo.",body:["El concurso buscaba reunir ideas para transformar la Plaza Portugal en un espacio lúdico e inclusivo. El llamado era abierto a todos los estudiantes de Arquitectura y Diseño; tuvo una muy buena convocatoria, a la cual se presentaron 33 propuestas.","La Plaza Portugal, ubicada en el barrio La Blanqueada, fue el espacio elegido para desarrollar el primer proyecto de la Fundación. El espacio escapaba a la escala de trabajo, pero contábamos con el apoyo de la empresa Ventura para comenzar.","El proyecto ganador del concurso, integrado por Catalina Radi, Elisa Porley, Ignacio Bianco y Simone Frieri, fue luego tutoreado por el arquitecto Iván Arcos, director de Estudio Cinco. Se destacaba por generar tres áreas diferentes que responden a distintos usos y permiten la convivencia de actividades, en consonancia con el objetivo de desarrollar la inclusión en un sentido amplio."]},
  plazajardinbotanico:{title:"Jardín Botánico",location:"Montevideo",image:images.botanico,photos:[images.botanicoGlobos,images.botanico],gallery:20,video:"QF3NpCXfmMA",map:"https://www.google.com/maps/d/u/0/edit?hl=es&mid=1JwDjqIUl8SmUsA_IYPt-7OqAEsKyaZY&ll=-34.89591158053271%2C-56.164647758638004&z=14",intro:"En conjunto con el Departamento de Cultura de la Intendencia de Montevideo, realizamos un nuevo espacio recreativo, accesible e inclusivo en el Jardín Botánico de Montevideo.",body:["El Jardín Botánico enseña sobre el respeto y el cuidado de la biodiversidad. Ahora también su plaza infantil es un espacio de enseñanza, donde los más pequeños pueden compartir la importancia de la inclusión en nuestro entorno.","En 2019 se llevó a cabo Arqatón, una maratón de Arquitectura convertida en laboratorio de ideas para crear espacios de juegos accesibles e inclusivos.","Arqatón fue una colaboración entre los organizadores de la Feria de la Construcción, la Intendencia de Montevideo, la Facultad de Arquitectura de la UDELAR, la Facultad de Arquitectura de la ORT, la SAU y el Municipio CH. Diez equipos trabajaron durante 20 horas consecutivas."]},
  vazquezledesma:{title:"Plaza Vázquez Ledesma",location:"Montevideo",image:images.vazquez,photos:[images.vazquezJuego,images.vazquezCano],gallery:15,video:"_HGrLaczEtE",intro:"En la esquina de Vázquez Ledesma y Benito Blanco se generó un espacio de oportunidad en el que trabajamos con el apoyo del Municipio CH.",body:["Se trató de un proyecto experimental: se diseñaron juegos a partir de materiales simples, económicos y de fácil mantenimiento, con la idea de que pudieran replicarse en cualquier barrio o rincón del país. Este espacio fue desarmado debido a que el predio era privado y fue cedido por un tiempo.","Aquí también se utilizaron ideas premiadas del concurso “Una plaza para todos”. El proyecto surge de la Primera Mención, del equipo integrado por Rodirgo Bracho, Alejandro Raftopulos y Lucrecia Vespa.","A partir de un único elemento constitutivo —caño rojo— se establece una secuencia de posibles escenas de juego. En primera instancia el equipo fue tutoreado por el arquitecto Roberto Moraes, director de Kimelman-Moraes."]},
  plazaituzaingo:{title:"Plaza Ituzaingó",location:"Montevideo",image:images.ituzaingo,photos:[images.ituzaingoJuego,images.ituzaingoTrepar],gallery:17,video:"6u7OeDcsEdw",intro:"En la esquina de Nicolás Piaggio y Saldanha da Gama se construyó un nuevo espacio de juegos accesible e inclusivo junto a la Intendencia de Montevideo.",body:["Este proyecto se originó en el marco de ArqAtón, un innovador concurso de ideas organizado en 2019 como parte de la Feria de la Construcción.","Diez equipos de tres personas trabajaron durante 20 horas continuas para diseñar propuestas arquitectónicas que promovieran la inclusión de niños y niñas con diferentes capacidades en espacios públicos.","El proyecto ganador destacó por su creatividad, funcionalidad y visión replicable. Plaza Ituzaingó fue financiada por Fundación Jazmín y la Intendencia de Montevideo."]},
  conciertoabeneficio:{title:"Concierto a beneficio",location:"Montevideo",image:images.family,gallery:15,video:"kySsI2fwxgI",intro:"El martes 3 de septiembre, Fundación Jazmín celebró los 15 años de Jazmín con un emotivo concierto sinfónico a beneficio en Movie Montevideo Shopping.",body:["El evento celebró el crecimiento de la joven que inspiró la fundación y recaudó fondos para crear un nuevo espacio de juegos inclusivo en el Hospital Pereira Rossell.","Desde 2015, Nadia Dib y Fabián Kopel trabajan para que todos los niños puedan disfrutar de espacios accesibles. La iniciativa de hamacas inclusivas ya recibió más de 500 solicitudes.","El concierto también marcó el anuncio de la Fundación Uruguaya de Neuropediatría Infantil (FUNI), liderada por los doctores Gabriel Gonzales y Alfredo Cerisola."]}
};

export function ProjectPage({ project }: { project: Project }) { return <main id="contenido"><PageHero eyebrow="Proyecto" title={project.title} text={project.location} image={project.image}/><section className="section"><div className="container content-grid"><aside><p className="eyebrow">Fundación Jazmín</p><p>{project.location}</p>{project.gallery&&<p>{project.gallery} fotografías publicadas</p>}{project.map&&<a className="button outline" href={project.map} target="_blank" rel="noreferrer">¿Cómo llegar? →</a>}</aside><article className="prose"><p className="large-text">{project.intro}</p>{project.body.map(p=><p key={p}>{p}</p>)}{project.video&&<><h2>Conocé el proyecto</h2><Video id={project.video} title={project.title}/></>}</article></div></section><section className="media-grid">{(project.photos||[project.image||images.children,images.event]).map((photo,i)=><img key={photo} src={photo} alt={i===0?`Proyecto ${project.title}`:`Actividad en ${project.title}`}/>)}</section><DonateBand/></main> }
