import type { Metadata } from "next";
import { images, PageHero, SectionTitle, Video } from "@/components/PageParts";
export const metadata:Metadata={title:"Quiénes somos"};
const suenos = [
  "Espacios de juegos para todos los niños en todos los barrios.",
  "Niños riendo, disfrutando, jugando e interactuando en todos los espacios públicos de nuestra ciudad.",
  "Espacios donde los padres puedan llevar a sus hijos a realizar las rehabilitaciones que necesiten, jugando, cerca de su casa y sin complejidades de traslado.",
  "Equipamientos inclusivos que no requieran mucho mantenimiento, en espacios protegidos y seguros.",
  "Una sociedad aprendiendo a vivir de forma solidaria, cuidando los espacios públicos.",
];
export default function Page(){return <main id="contenido"><PageHero eyebrow="Nuestra historia" title="La luz y la alegría de Jazmín." text="Una fundación nacida como un regalo a la sociedad." image={images.globos}/><section className="section"><div className="container content-grid"><aside><p className="eyebrow">Quiénes somos</p><p>Fundación Jazmín<br/>Uruguay · desde 2015</p></aside><article className="prose"><p className="large-text">Fundación Jazmín fue creada por los padres de Jazmín Kopel, Nadia Dib y Fabián Kopel, como un regalo a la sociedad en nombre de su hija y de todas las personas que la ayudaron y ayudan cada día.</p><p>Enfermeras, doctores, kinesiólogas, psicomotricistas, terapistas ocupacionales y, por supuesto, abuelos, tíos, primos, amigos y tantas personas queridas más.</p><p>Jazmín hoy tiene 15 años y desde que nació se vio comprometido su desarrollo físico e intelectual, no así su capacidad de amar y ser amada.</p><p>La Fundación Jazmín tiene como inspiración la luz y la alegría que Jazmín transmite cada día. Es su fuerza la que nos impulsa a ver la vida con generosidad y agradecimiento, a seguir adelante a pesar de cualquier obstáculo y a confiar en que todo es posible, incluso un mundo mejor.</p><Video id="KUMnoRaSras" title="Historia de Fundación Jazmín"/></article></div></section><section className="section intro-section suenos"><div className="container suenos-grid"><div className="suenos-titulo"><SectionTitle eyebrow="Nuestros sueños" title="Nos imaginamos una ciudad mejor. Nos imaginamos un mundo mejor."/></div><ol className="suenos-lista">{suenos.map((s)=><li key={s}><p>{s}</p></li>)}</ol></div></section></main>}
